services:
  - type: web
    name: asset-verification-app
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/UNI_ASSETS.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
